# Generated by Django 4.2.2 on 2023-08-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_art', models.CharField(max_length=100)),
                ('colores', models.IntegerField()),
                ('imagen_1', models.ImageField(upload_to='productos/')),
                ('imagen_2', models.ImageField(upload_to='productos/')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
